GET http://localhost:5159/todos

###

GET http://localhost:5159/todo/2

###

PUT http://localhost:5159/todo/2
Content-Type: application/json

{
    "name": "Todo 5",
    "description": "This is Todo 5",
    "IsComplete": true
}

###

POST  http://localhost:5159/todo
Content-Type: application/json

{
    "name": "Todo 8",
    "description": "This is Todo 8",
    "IsComplete": true
}

###

DELETE http://localhost:5159/todo/2

###
GET http://localhost:5159/todos/completed